### ISSUE TITLE
Simple Demo Page

### ISSUE THREAD

**Issue by miraclx** [nearprotocol/near-seed-phrase#31]
A couple of months ago, I created a simple front end for this that's hosted on GitHub Pages, and since it's been useful for me, I decided to mention it here.

Here's the active branch: https://github.com/near/near-seed-phrase/tree/gh-pages

Not sure who holds ownership to this repo, but if we want to make this happen, someone would have to manually turn on GitHub Pages for this repo, and point it to the `gh-pages` branch.

In the meantime, here's a demo on my fork: https://miraclx.github.io/near-seed-phrase/

<img width="661" alt="CleanShot 2022-09-21 at 05 45 41@2x" src="https://user-images.githubusercontent.com/16881812/191395719-e543525a-20d0-449f-9cad-dd85e6e5ea51.png">

**Comment by frol** [comment]
@miraclx Thanks!

Done: https://near.github.io/near-seed-phrase/
