### ISSUE TITLE
Add Type Declaration

### ISSUE THREAD

**Issue by bh2smith** [nearprotocol/near-seed-phrase#38]
The type declaration is not included in the dist/ directory. It might be as simple as that.
This would resolve dependents lint errors:

Could not find a declaration file for module 'near-seed-phrase'. 'node_modules/.pnpm/near-seed-phrase@0.2.0/node_modules/near-seed-phrase/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/near-seed-phrase` if it exists or add a new declaration (.d.ts) file containing `declare module 'near-seed-phrase';`ts(7016)

**Comment by frol** [comment]
@bh2smith Consider authoring a PR and I am happy to review and release it

**Comment by bh2smith** [comment]
Good thinking! Here we are: https://github.com/near/near-seed-phrase/pull/39
